export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN';
export const ADD_TO_CART = 'ADD_TO_CART';
export const CLEAR_ITEM = 'CLEAR_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const UPDATE_COLLECTIONS = 'UPDATE_COLLECTIONS';
